version: '3.1'
services:
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      API_URL: http://localhost:3000/

  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://authenticator:mysecretpassword@db:5432/postgres
      PGRST_DB_SCHEMAS: api
      PGRST_DB_ANON_ROLE: "web_anon"
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@here.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - "./pgadmin:/var/lib/pgadmin"
      - "./pgadmin4/servers.json:/pgadmin4/servers.json"

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - "./pgdata:/var/lib/postgresql/data"